steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/total-messenger-321308/appengine/default.20210820t071215', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/total-messenger-321308/appengine/default.20210820t071215']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'flask', '--image', 'gcr.io/total-messenger-321308/appengine/default.20210820t071215', '--region', 'us-central1', '--platform', 'managed']
images:
- gcr.io/total-messenger-321308/appengine/default.20210820t071215